CROSSPREFIX=i686-elf

CC=$(CROSSPREFIX)-gcc
CXX=$(CROSSPREFIX)-g++
LD=$(CROSSPREFIX)-ld
AS=$(CROSSPREFIX)-as
AR=$(CROSSPREFIX)-ar

OPTFLAGS=-g

ASFLAGS=$(OPTFLAGS)
CFLAGS=$(OPTFLAGS) -ffreestanding -Wall -Wextra -mgeneral-regs-only
CXXFLAGS=$(CFLAGS) -fno-rtti -fno-exceptions
LDFLAGS=$(OPTFLAGS) -L/home/nekosu/osdev/inst/lib/gcc/i686-elf/11.2.0 -lgcc