CROSSTOOLPATH=/home/nekosu/osdev/inst
CROSSPREFIX=$(CROSSTOOLPATH)/bin/i686-elf

CC=$(CROSSPREFIX)-gcc
CXX=$(CROSSPREFIX)-g++
LD=$(CROSSPREFIX)-ld
AS=$(CROSSPREFIX)-as
AR=$(CROSSPREFIX)-ar

OPTFLAGS=-g

ASFLAGS=$(OPTFLAGS)
CFLAGS=$(OPTFLAGS) -ffreestanding -Wall -Wextra -mgeneral-regs-only -I$(ROOT)/kernel/nos
CXXFLAGS=$(CFLAGS) -fno-rtti -fno-exceptions
LDFLAGS=$(OPTFLAGS) -L$(CROSSTOOLPATH)/lib/gcc/i686-elf/11.2.0 -lgcc